// GENERATED by scripts/build-impact-stickers.mjs. Do not edit by hand.
//
// One badge per CREATE level: 43 levels, 43 stickers, in curriculum order.
//
// Each is a real Code Ninjas IMPACT achievement icon, under the name Code
// Ninjas gave it, taken from the level it belongs to. The source has 218
// achievements, four to nine per level; each level puts one forward and the
// rest stay in the assets folder. Which one is an editorial choice recorded in
// the build script's LEVEL_BADGES table, made by reading the level's poster
// topic and quest — not computed, because a keyword score put "Layer Cake" on
// Events! and that is how the old set went wrong.
//
// This file used to hold 35 hand-written milestones over belt spot art, with
// invented titles ("First Coder") on artwork that came from a different level
// than the one it claimed. Those are gone.
//
// WHAT A STICKER CLAIMS: that the level is finished. Nothing more. The
// achievements themselves are awarded inside MakeCode for specific in-game
// actions that never reach DojoLink, so no surface says a ninja personally
// unlocked this one — the badge stands for the level, and every requirement
// line says so ("Complete White Belt Level 1").
// See lib/stickerProgress.js for the one definition of "earned".

const a = (belt, level, title) => {
  const id = `${belt.toLowerCase()}-${level}-${title.toLowerCase().replace(/['’]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')}`;
  return { id, belt, level, title, src: `/impact/${id}.png` };
};

export const CREATE_STICKERS = [
  // White belt
  a('White', 1, "First Words"),
  a('White', 2, "Story Teller"),
  a('White', 3, "Taking Control"),
  a('White', 4, "A Whole New Kind of Sprite"),

  // Yellow belt
  a('Yellow', 1, "Keeping Track"),
  a('Yellow', 2, "I Like to Move It, Move It"),
  a('Yellow', 3, "To Be or Not to Be"),
  a('Yellow', 4, "Saturday Morning Cartoons"),

  // Orange belt
  a('Orange', 1, "X and Y Marks the Spot"),
  a('Orange', 2, "New Tile Who Dis"),
  a('Orange', 3, "Making a List"),
  a('Orange', 4, "Once More, With Feeling"),
  a('Orange', 5, "Don't Forget to Call"),

  // Green belt
  a('Green', 1, "Hop, Skip and a Jump"),
  a('Green', 2, "All or Nothing"),
  a('Green', 3, "Card Catalog"),
  a('Green', 4, "GPS"),
  a('Green', 5, "Setting the Bar"),

  // Blue belt
  a('Blue', 1, "Opening Line"),
  a('Blue', 2, "Comment, Like and Subscribe"),
  a('Blue', 3, "Framing the Discussion"),
  a('Blue', 4, "Nestled Brackets"),
  a('Blue', 5, "Let There Be Variables"),
  a('Blue', 6, "Comparatively Speaking"),

  // Purple belt
  a('Purple', 1, "A Meeting of the Kinds"),
  a('Purple', 2, "Here We Go Again"),
  a('Purple', 3, "Array of Sunshine"),
  a('Purple', 4, "Arrays All the Way Down"),
  a('Purple', 5, "Calling All Functions"),
  a('Purple', 6, "Earworm"),

  // Brown belt
  a('Brown', 1, "Carefully Curated"),
  a('Brown', 2, "A Glyph in the System"),
  a('Brown', 3, "Checkin' It Twice"),
  a('Brown', 4, "Swatch and Learn"),
  a('Brown', 5, "Work of Art"),
  a('Brown', 6, "The Gang's All Here!"),
  a('Brown', 7, "Frame by Frame"),
  a('Brown', 8, "A Whole New World"),
  a('Brown', 9, "Choose Your Adventure"),
  a('Brown', 10, "Birds Eye View"),

  // Red belt
  a('Red', 1, "Hole in One"),
  a('Red', 2, "Tower Power!"),

  // Black belt
  a('Black', 1, "Something to be Proud Of"),
];

// Belt order is the order of the array, which is curriculum order.
export const STICKER_BELTS = [...new Set(CREATE_STICKERS.map((item) => item.belt))];

export function stickersForBelt(belt) {
  return CREATE_STICKERS.filter((item) => item.belt === belt);
}

export function stickerRequirement({ belt, level }) {
  return `Complete ${belt} Belt Level ${level}`;
}
