// GENERATED by scripts/build-module-stickers.mjs. Do not edit by hand.
//
// One sticker per module of JR, Robotics Academy and AI Academy: 38 in all.
//
// NOT ACHIEVEMENTS, and the difference matters. The CREATE book's badges are
// real Code Ninjas achievements, awarded in MakeCode, under the names Code
// Ninjas gave them. There is no equivalent list for these three programs, so
// these are DojoLink's own: the title names the MODULE, written from the
// lessons inside it, and the art is an IMPACT icon the CREATE book did not
// take, shown without its own title because that title belongs to a CREATE
// level. Nothing in the UI calls them achievements.
//
// WHAT A STICKER CLAIMS: that the module is finished — every lesson in it
// logged as Completed. See lib/moduleStickerProgress.js for the one
// definition of "earned".
//
// `moduleName` is the curriculum's real name, placeholders and all ("Module 6",
// "VG 2"), because it is the key: `progress_logs` stores it as text and the
// database is deliberately not renamed. `title` is what a parent reads.

// `id` IS THE FILE NAME, written out rather than rebuilt from the parts. It
// used to be derived here, from the same three fields the build script slugs,
// and the two expressions did not agree about a program with no kit: the
// build wrote ai-academy-module-1.png and this asked for
// ai-academy-null-module-1.png. Nine broken stickers, and nothing that could
// have caught it, because both sides looked right on their own.
const m = (id, program, subProgram, moduleName, title) => ({
  id,
  program,
  subProgram,
  moduleName,
  title,
  get src() { return `/modules/${this.id}.png`; },
});

export const MODULE_STICKERS = [

  // AI Academy
  m("ai-academy-module-1", "AI Academy", null, "Module 1", "Behind the Curtain"),
  m("ai-academy-module-2", "AI Academy", null, "Module 2", "Painting by Numbers"),
  m("ai-academy-module-3", "AI Academy", null, "Module 3", "Ghostwriter"),
  m("ai-academy-module-4", "AI Academy", null, "Module 4", "Out in the Wild"),
  m("ai-academy-module-5", "AI Academy", null, "Module 5", "Vibe Check"),
  m("ai-academy-module-6", "AI Academy", null, "Module 6", "Player Two"),
  m("ai-academy-module-7", "AI Academy", null, "Module 7", "Brains on Board"),
  m("ai-academy-module-8", "AI Academy", null, "Module 8", "Trust, but Verify"),
  m("ai-academy-module-9", "AI Academy", null, "Module 9", "Back to the Drawing Board"),

  // JR · JR Coding
  m("jr-jr-coding-module-1", "JR", "JR Coding", "Module 1", "One Step at a Time"),
  m("jr-jr-coding-module-2", "JR", "JR Coding", "Module 2", "Bug Hunt"),
  m("jr-jr-coding-module-3", "JR", "JR Coding", "Module 3", "Round and Round"),
  m("jr-jr-coding-module-4", "JR", "JR Coding", "Module 4", "Break It Down"),
  m("jr-jr-coding-module-5", "JR", "JR Coding", "Module 5", "Step by Step by Step"),
  m("jr-jr-coding-module-6", "JR", "JR Coding", "Module 6", "On Your Signal"),
  m("jr-jr-coding-module-7", "JR", "JR Coding", "Module 7", "If You Say So"),
  m("jr-jr-coding-module-8", "JR", "JR Coding", "Module 8", "First In, First Out"),
  m("jr-jr-coding-module-9", "JR", "JR Coding", "Module 9", "Two Heads, One Keyboard"),
  m("jr-jr-coding-module-10", "JR", "JR Coding", "Module 10", "Now You Make One"),

  // JR · Snap Circuits
  m("jr-snap-circuits-elenco", "JR", "Snap Circuits", "Elenco", "Complete the Circuit"),

  // Robotics Academy · LEGO Spike Essentials
  m("robotics-academy-lego-spike-essentials-e-1", "Robotics Academy", "LEGO Spike Essentials", "E 1", "Planes, Trains and Swamp Boats"),
  m("robotics-academy-lego-spike-essentials-e-2", "Robotics Academy", "LEGO Spike Essentials", "E 2", "A Machine for That"),
  m("robotics-academy-lego-spike-essentials-e-3", "Robotics Academy", "LEGO Spike Essentials", "E 3", "Step Right Up"),
  m("robotics-academy-lego-spike-essentials-1-great-adventure", "Robotics Academy", "LEGO Spike Essentials", "1. Great Adventure", "Great Adventure"),
  m("robotics-academy-lego-spike-essentials-2-amazing-amusement-park", "Robotics Academy", "LEGO Spike Essentials", "2. Amazing Amusement Park", "Amazing Amusement Park"),
  m("robotics-academy-lego-spike-essentials-3-reimagine-the-world", "Robotics Academy", "LEGO Spike Essentials", "3. Reimagine the World", "Reimagine the World"),
  m("robotics-academy-lego-spike-essentials-4-useful-inventions", "Robotics Academy", "LEGO Spike Essentials", "4. Useful Inventions", "Useful Inventions"),
  m("robotics-academy-lego-spike-essentials-5-animal-friends", "Robotics Academy", "LEGO Spike Essentials", "5. Animal Friends", "Animal Friends"),

  // Robotics Academy · LEGO Spike Prime
  m("robotics-academy-lego-spike-prime-p-1", "Robotics Academy", "LEGO Spike Prime", "P 1", "Ready, Set, Build"),
  m("robotics-academy-lego-spike-prime-p-2", "Robotics Academy", "LEGO Spike Prime", "P 2", "Reading the Room"),
  m("robotics-academy-lego-spike-prime-p-3", "Robotics Academy", "LEGO Spike Prime", "P 3", "Signed, Sealed, Delivered"),
  m("robotics-academy-lego-spike-prime-p-4", "Robotics Academy", "LEGO Spike Prime", "P 4", "Boot Camp"),

  // Robotics Academy · Ozobot Evo
  m("robotics-academy-ozobot-evo-o-1", "Robotics Academy", "Ozobot Evo", "O 1", "Color Me Coded"),
  m("robotics-academy-ozobot-evo-o-2", "Robotics Academy", "Ozobot Evo", "O 2", "Reading Between the Lines"),

  // Robotics Academy · VEX GO
  m("robotics-academy-vex-go-vg-1", "Robotics Academy", "VEX GO", "VG 1", "The Simple Life"),
  m("robotics-academy-vex-go-vg-2", "Robotics Academy", "VEX GO", "VG 2", "Life on Mars"),
  m("robotics-academy-vex-go-vg-3", "Robotics Academy", "VEX GO", "VG 3", "Look, No Hands"),
  m("robotics-academy-vex-go-vg-4", "Robotics Academy", "VEX GO", "VG 4", "Somebody's Got to Do It"),
];

// Every sticker a program has, in curriculum order.
export function stickersForProgram(program) {
  return MODULE_STICKERS.filter((s) => s.program === program);
}
